app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


api_login_check:
    path: /api/login_check

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc


user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

userById:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

team:
    resource: "@AppBundle/Resources/config/routing_team.yml"
    prefix:   /team

category_project:
    resource: "@AppBundle/Resources/config/routing_category_project.yml"
    prefix:   /category_project

userSpecial:
    path:     /user/{id}
    defaults: { _controller: AppBundle\Controller\UserController::getUserById }
    methods:  [GET]

user_all:
    path:     /user/allUsers
    defaults: { _controller: AppBundle\Controller\UserController::listUsers }
    methods:  [GET]


user_create:
    path:     /user/createUser
    defaults: { _controller: AppBundle\Controller\UserController::createUser }
    methods:  [POST]

facture_list:
    path:     /facture
    defaults: { _controller: AppBundle\Controller\FactureController::indexAction }
    methods:  [GET]

facture_create:
    path:     /facture/new
    defaults: { _controller: AppBundle\Controller\FactureController::newAction }
    methods:  [POST]

factureById:
    path:     /facture/{id}
    defaults: { _controller: AppBundle\Controller\FactureController::getFactureById }
    methods:  [GET]



