<?php

namespace AppBundle\Repository;

/**
 * CategoryProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
