project_GET:
  path:     /
  defaults: { _controller: AppBundle:Projet:index }
  methods : [GET]

project_POST:
  path:     /new/{id}
  defaults: { _controller: AppBundle:Projet:new }

project_GET_ById:
  path:     /get/{id}
  defaults: { _controller: AppBundle:Projet:showByid }

project_PUT_ById:
  path:     /edit/{id}
  defaults: { _controller: AppBundle:Projet:edit }
  methods : [POST]

project_DELETE_ById:
  path:     /delete/{id}
  defaults: { _controller: AppBundle:Projet:delete }

project_Status:
  path:     /activeProjects
  defaults: { _controller: AppBundle:Projet:active }
