client_GET:
  path:     /
  defaults: { _controller: AppBundle:Client:index }
  methods : [GET]

client_POST:
  path:     /new
  defaults: { _controller: AppBundle:Client:new }

client_GET_ById:
  path:     /{id}
  defaults: { _controller: AppBundle:Client:showByid }

client_PUT_ById:
  path:     /{id}
  defaults: { _controller: AppBundle:Client:edit }
  methods : [POST]

client_DELETE_ById:
  path:     /{id}
  defaults: { _controller: AppBundle:Client:delete }
